---
title: "A User-Friendly U.S. Census Browser for R"
author: "Kiegan Rice"
output:
  pdf_document: default
bibliography: bibliography.bib
header-includes:
- \usepackage{setspace}
- \doublespacing
fontsize: 11pt
---


```{r, echo = FALSE}
#Email Univ. of Virginia Library
#  * done, they are going to follow up with more information

# change name of R package?!
#Is there a way to set up a warning for variables that might change names over time?

#Visualizations 
#  - Compare slaves to free (color scale like election example)
#  - Use USAboundaries
#  - Facet when using different variables (slaves, free, etc)
#  - Log scale for numbers?
  
#Questions for Dr. Hofmann about Example:  
#  - Could we do a discrete scale that is the same for all years? May be hard since the population increases over time, but it would allow us to compare charts across years. 
#  - Years comparing 'SLAVES', 'TOTAL.FREE.COLORED.PERSONS', and 'PERC.AFRICAN.AMERICANS.FREE', can we put these next to each other or just look at them individually?


#Write-up

# Citations - how should I do them? Example of how I have been doing them...
```

## Introduction  
$\quad$ 
- How important census data is  

- Transparency and availability  

- Ever-changing census means that we have different information in different years  

- To get complete information, we have to be able to see what information we have and don't have  


$\quad$ An inherent problem in census data is that a country's census changes over time; the variables collected, how they are collected, and even the locations they are collected for change as the country is formed, and subsequently grows and changes. The United States census data is no exception to this rule. In a little under two and a half centuries, the census has taken on many different forms. Data on occupations has transformed as the employment landscape has changed; new states have been formed, the most recent being within the last 100 years; definitions of various demographic groups and the terminology used to describe them have been updated as the demographic makeup of the country has changed.



## Background (Literature Review)  
$\quad$ The University of Virginia Library hosted a "Historical Census Browser" for many years that allowed users to search United States Census Data for use in research, teaching, and personal inquiry. The data included data on various aspects of the U.S. population from the 1790 Census through the 1960 Census. This Historical Census Browser was free and available for use for anyone with an internet connection. This Census Browser allowed a user to peruse available topics for each census year, at both the state and county levels. The Historical Census Browser was taken down on December 31, 2016, with the county-level aggregated data becoming unavailable several months before this. The source was widely used, with several other university libraries and educational resources including University of California Santa Barbara, University of Pennsylvania, University of Michigan, and the Smithsonian's History Explorer directing researchers to use the University of Virginia source. 

## Work  


### Motivation  
The University of Virginia Libraries website now directs users to "Social Explorer" or the "National Historical Geographic Information System" website. However, neither resource provides the full advantages that the Historical Census Browser offered: a free-to-use and user-friendly data browser that allows users to choose which data they are interested in using, and download the complete records for their own independent use.  



### Description  
Although the county-level data had already been removed from the website, the state-level aggregated records for each decennial census from 1790 through 1960 were captured from the website in September of 2016 and saved as raw data with the intent to create a resource for R users that allowed the same main functionalities of the original University of Virginia Historical Census Browser, streamlined for easy data searches and data management.  

- What the package includes and what capabilities the Shiny app has  


### Example  
We can easily use the Shiny app to search for a topic of interest, find the data we want, download state-level information, and tell a visual story of populations in the United States over time.  


### Implementation  
How to use it - this is the most technical part  


## Discussion of Future Work  
- County-level data would be great  
- Current data (up to 2010 Census)  


## References  


